// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd-VAtCYs67P6cKqdtN9Lt8tq9UE9R1tM',
    appId: '1:423049162614:web:3b96f71d23dd384b859457',
    messagingSenderId: '423049162614',
    projectId: 'pickpoker-db6da',
    authDomain: 'pickpoker-db6da.firebaseapp.com',
    databaseURL: 'https://pickpoker-db6da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pickpoker-db6da.appspot.com',
    measurementId: 'G-5W6188LKP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqr2dSO2PALeGXu_x5GdtbzJDXZigq2A',
    appId: '1:423049162614:android:18e57df453e3e774859457',
    messagingSenderId: '423049162614',
    projectId: 'pickpoker-db6da',
    databaseURL: 'https://pickpoker-db6da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pickpoker-db6da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOlFMxSEReO66KYaLHvFYuoOXspPj53Ls',
    appId: '1:423049162614:ios:e26480b71bf2cdfa859457',
    messagingSenderId: '423049162614',
    projectId: 'pickpoker-db6da',
    databaseURL: 'https://pickpoker-db6da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pickpoker-db6da.appspot.com',
    iosClientId: '423049162614-l3pchaoupciudf8h5k8ptbscmc10gu8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickPoker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOlFMxSEReO66KYaLHvFYuoOXspPj53Ls',
    appId: '1:423049162614:ios:e26480b71bf2cdfa859457',
    messagingSenderId: '423049162614',
    projectId: 'pickpoker-db6da',
    databaseURL: 'https://pickpoker-db6da-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pickpoker-db6da.appspot.com',
    iosClientId: '423049162614-l3pchaoupciudf8h5k8ptbscmc10gu8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickPoker',
  );
}
